#!/usr/bin/env python3
from playserver import webserver
from playserver import globalconfig

if __name__ == "__main__":
	webserver.app.run(host = globalconfig.config["host"], 
		port = globalconfig.config["webserver-port"])
